"""
End-to-end Threat Scenario Tests
===================================
Each test:
  1. Loads a synthetic test image (generated by generate_test_images.py)
  2. Mocks the YOLO model to return ground-truth detections for that image
  3. Runs the full pipeline:  frame → _process_frame → alert_queue → AlertDispatcher
  4. Asserts the correct incident type, severity, and response actions

Run the image generator first (or rely on pytest auto-generation via the
session-scoped fixture below):
    python tests/generate_test_images.py
"""
import json
import queue
import time
from pathlib import Path
from unittest.mock import patch

import cv2
import numpy as np
import pytest

from inference_engine import AlertDispatcher, CameraProcessor, THREAT_CONFIG
from tests.conftest import CLASS_IDS, make_results
from tests.generate_test_images import (
    OUTPUT_DIR,
    generate_all,
    scene_loitering,
    scene_brawl,
    scene_fire,
    scene_smoke,
    scene_abandoned_bag,
    scene_crowd_surge,
    scene_weapon,
    scene_vehicle_intrusion,
    scene_graffiti,
    scene_suspicious_package,
    scene_person_with_fire,
    scene_multiple_loiterers,
)


# ─── SESSION FIXTURE: ensure test images exist ────────────────────────────────

@pytest.fixture(scope="session", autouse=True)
def ensure_test_images():
    """Generate synthetic test images once per test session if not present."""
    if not OUTPUT_DIR.exists() or not (OUTPUT_DIR / "manifest.json").exists():
        generate_all(OUTPUT_DIR)
    yield
    # No teardown — images are kept for inspection


@pytest.fixture
def dispatcher(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    return AlertDispatcher()


# ─── HELPERS ──────────────────────────────────────────────────────────────────

def _build_processor(mock_model, alert_queue, tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    return CameraProcessor("CAM-TEST", "synthetic", mock_model, alert_queue)


def _run_scenario(
    processor,
    alert_queue,
    img: np.ndarray,
    detections: list,
    t: float = 1_000_000.0,
):
    """Inject detections into the mock model and process the frame."""
    processor.model.track.return_value = make_results(detections)
    with patch("inference_engine.time.time", return_value=t):
        processor._process_frame(img, frame_idx=2)


def _drain_queue(q: queue.Queue):
    incidents = []
    while not q.empty():
        incidents.append(q.get_nowait())
    return incidents


def _make_det(class_name: str, bbox, track_id: int, conf: float = 0.90):
    return {
        "cls_id":   CLASS_IDS[class_name],
        "conf":     conf,
        "bbox":     bbox,
        "track_id": track_id,
    }


# ─── SCENARIO TESTS ───────────────────────────────────────────────────────────

class TestLoiteringScenario:
    # Use a realistic epoch base so the 60-second rate-limiter (which compares
    # against 0 for "never alerted") doesn't suppress the first incident.
    BASE_T = 1_000_000.0

    def test_loitering_detected_after_30s(
        self, mock_model, alert_queue, tmp_path, monkeypatch
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_loitering()
        bbox = gt[0]["bbox"]

        # Seed tracker at BASE_T
        _run_scenario(proc, alert_queue, img,
                      [_make_det("person", bbox, track_id=1)], t=self.BASE_T)
        assert alert_queue.empty(), "No loitering before 30 s"

        # Same position 31 s later
        _run_scenario(proc, alert_queue, img,
                      [_make_det("person", bbox, track_id=1)], t=self.BASE_T + 31.0)

        incidents = _drain_queue(alert_queue)
        assert any(i.threat_type == "loitering" for i in incidents), \
            "Loitering should be flagged after 31 s"

    def test_loitering_severity_is_medium(
        self, mock_model, alert_queue, tmp_path, monkeypatch
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_loitering()
        bbox = gt[0]["bbox"]

        _run_scenario(proc, alert_queue, img,
                      [_make_det("person", bbox, track_id=1)], t=self.BASE_T)
        _run_scenario(proc, alert_queue, img,
                      [_make_det("person", bbox, track_id=1)], t=self.BASE_T + 31.0)

        incidents = _drain_queue(alert_queue)
        loitering = [i for i in incidents if i.threat_type == "loitering"]
        assert loitering[0].severity == "medium"


class TestBrawlScenario:
    def test_brawl_detected_immediately(
        self, mock_model, alert_queue, tmp_path, monkeypatch
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_brawl()
        bbox = gt[0]["bbox"]

        _run_scenario(proc, alert_queue, img,
                      [_make_det("brawl", bbox, track_id=2)])

        incidents = _drain_queue(alert_queue)
        assert any(i.threat_type == "brawl" for i in incidents)

    def test_brawl_triggers_police_notification(
        self, mock_model, alert_queue, tmp_path, monkeypatch, dispatcher
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_brawl()
        _run_scenario(proc, alert_queue, img,
                      [_make_det("brawl", gt[0]["bbox"], track_id=2)])

        inc = alert_queue.get_nowait()
        dispatcher.dispatch(inc)
        assert "notify:police" in inc.actions


class TestFireScenario:
    def test_fire_detected_immediately(
        self, mock_model, alert_queue, tmp_path, monkeypatch
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_fire()
        _run_scenario(proc, alert_queue, img,
                      [_make_det("fire", gt[0]["bbox"], track_id=3)])

        incidents = _drain_queue(alert_queue)
        assert any(i.threat_type == "fire" for i in incidents)

    def test_fire_triggers_sprinkler_and_all_notifications(
        self, mock_model, alert_queue, tmp_path, monkeypatch, dispatcher
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_fire()
        _run_scenario(proc, alert_queue, img,
                      [_make_det("fire", gt[0]["bbox"], track_id=3)])

        inc = alert_queue.get_nowait()
        dispatcher.dispatch(inc)
        assert "deter:sprinkler_trigger" in inc.actions
        assert "notify:personnel"         in inc.actions
        assert "notify:police"            in inc.actions
        assert "notify:fire"              in inc.actions


class TestSmokeScenario:
    def test_smoke_detected_immediately(
        self, mock_model, alert_queue, tmp_path, monkeypatch
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_smoke()
        _run_scenario(proc, alert_queue, img,
                      [_make_det("smoke", gt[0]["bbox"], track_id=4)])

        incidents = _drain_queue(alert_queue)
        assert any(i.threat_type == "smoke" for i in incidents)
        assert incidents[0].severity == "high"


class TestAbandonedBagScenario:
    def test_abandoned_bag_detected(
        self, mock_model, alert_queue, tmp_path, monkeypatch
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_abandoned_bag()
        _run_scenario(proc, alert_queue, img,
                      [_make_det("abandoned_bag", gt[0]["bbox"], track_id=5)])

        incidents = _drain_queue(alert_queue)
        assert any(i.threat_type == "abandoned_bag" for i in incidents)

    def test_abandoned_bag_triggers_police_alert(
        self, mock_model, alert_queue, tmp_path, monkeypatch, dispatcher
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_abandoned_bag()
        _run_scenario(proc, alert_queue, img,
                      [_make_det("abandoned_bag", gt[0]["bbox"], track_id=5)])

        inc = alert_queue.get_nowait()
        dispatcher.dispatch(inc)
        assert "notify:police" in inc.actions


class TestCrowdSurgeScenario:
    def test_crowd_surge_detected(
        self, mock_model, alert_queue, tmp_path, monkeypatch
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_crowd_surge()
        _run_scenario(proc, alert_queue, img,
                      [_make_det("crowd_surge", gt[0]["bbox"], track_id=6)])

        incidents = _drain_queue(alert_queue)
        assert any(i.threat_type == "crowd_surge" for i in incidents)
        assert incidents[0].severity == "medium"


class TestWeaponScenario:
    def test_weapon_detected_immediately(
        self, mock_model, alert_queue, tmp_path, monkeypatch
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_weapon()
        _run_scenario(proc, alert_queue, img,
                      [_make_det("weapon", gt[0]["bbox"], track_id=7)])

        incidents = _drain_queue(alert_queue)
        assert any(i.threat_type == "weapon" for i in incidents)

    def test_weapon_is_critical_and_locks_gates(
        self, mock_model, alert_queue, tmp_path, monkeypatch, dispatcher
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_weapon()
        _run_scenario(proc, alert_queue, img,
                      [_make_det("weapon", gt[0]["bbox"], track_id=7)])

        inc = alert_queue.get_nowait()
        dispatcher.dispatch(inc)
        assert inc.severity == "critical"
        assert "deter:lock_gates" in inc.actions
        assert "notify:police"    in inc.actions


class TestVehicleIntrusionScenario:
    def test_vehicle_intrusion_detected(
        self, mock_model, alert_queue, tmp_path, monkeypatch
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_vehicle_intrusion()
        _run_scenario(proc, alert_queue, img,
                      [_make_det("vehicle_intrusion", gt[0]["bbox"], track_id=8)])

        incidents = _drain_queue(alert_queue)
        assert any(i.threat_type == "vehicle_intrusion" for i in incidents)

    def test_vehicle_intrusion_deploys_barrier(
        self, mock_model, alert_queue, tmp_path, monkeypatch, dispatcher
    ):
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_vehicle_intrusion()
        _run_scenario(proc, alert_queue, img,
                      [_make_det("vehicle_intrusion", gt[0]["bbox"], track_id=8)])

        inc = alert_queue.get_nowait()
        dispatcher.dispatch(inc)
        assert "deter:barrier_deploy" in inc.actions


class TestGraffitiScenario:
    def test_graffiti_vandalism_not_in_threat_config_no_incident(
        self, mock_model, alert_queue, tmp_path, monkeypatch
    ):
        """graffiti_vandalism is a training class but NOT in THREAT_CONFIG, so
        _process_frame skips it. This test documents current behaviour and
        serves as a guard: if THREAT_CONFIG is extended, this test must be
        updated to assert the incident IS raised."""
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_graffiti()
        _run_scenario(proc, alert_queue, img,
                      [_make_det("graffiti_vandalism", gt[0]["bbox"], track_id=9)])

        incidents = _drain_queue(alert_queue)
        # Expect zero incidents because class is not in THREAT_CONFIG
        assert not any(i.threat_type == "graffiti_vandalism" for i in incidents), (
            "graffiti_vandalism should produce no incidents until added to THREAT_CONFIG"
        )

    def test_graffiti_image_is_valid(self):
        """Synthetic graffiti image is well-formed regardless of inference config."""
        img, _, gt = scene_graffiti()
        assert img.shape == (480, 640, 3)
        assert gt[0]["class"] == "graffiti_vandalism"


class TestSuspiciousPackageScenario:
    def test_suspicious_package_not_in_threat_config_no_incident(
        self, mock_model, alert_queue, tmp_path, monkeypatch
    ):
        """suspicious_package is a training class but NOT in THREAT_CONFIG, so
        _process_frame skips it. This test documents current behaviour and
        serves as a guard: if THREAT_CONFIG is extended, this test must be
        updated to assert the incident IS raised."""
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_suspicious_package()
        _run_scenario(proc, alert_queue, img,
                      [_make_det("suspicious_package", gt[0]["bbox"], track_id=11)])

        incidents = _drain_queue(alert_queue)
        assert not any(i.threat_type == "suspicious_package" for i in incidents), (
            "suspicious_package should produce no incidents until added to THREAT_CONFIG"
        )

    def test_suspicious_package_image_is_valid(self):
        """Synthetic package image is well-formed regardless of inference config."""
        img, _, gt = scene_suspicious_package()
        assert img.shape == (480, 640, 3)
        assert gt[0]["class"] == "suspicious_package"


# ─── MULTI-THREAT SCENARIOS ───────────────────────────────────────────────────

class TestMultiThreatScenarios:
    def test_person_with_fire_raises_both_incidents(
        self, mock_model, alert_queue, tmp_path, monkeypatch
    ):
        """Arson scenario: person + fire in same frame → both threats flagged."""
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_person_with_fire()

        t0 = 1_000_000.0
        # Seed person at t0
        person_det = _make_det("person", gt[0]["bbox"], track_id=1)
        fire_det   = _make_det("fire",   gt[1]["bbox"], track_id=2)
        _run_scenario(proc, alert_queue, img, [person_det, fire_det], t=t0)
        # Fire → immediate. Person → not yet (< 30 s).
        incidents_0 = _drain_queue(alert_queue)
        types_0 = {i.threat_type for i in incidents_0}
        assert "fire" in types_0, "Fire should be flagged immediately"

        # 31 s later → person now loitering
        _run_scenario(proc, alert_queue, img, [person_det, fire_det], t=t0 + 31.0)
        incidents_1 = _drain_queue(alert_queue)
        types_1 = {i.threat_type for i in incidents_1}
        assert "loitering" in types_1, "Loitering should be flagged after 31 s"

    def test_multiple_loiterers_each_flagged(
        self, mock_model, alert_queue, tmp_path, monkeypatch
    ):
        """Two people loitering independently should each generate an incident."""
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img, _, gt = scene_multiple_loiterers()

        t0 = 1_000_000.0
        dets = [_make_det("person", d["bbox"], track_id=i + 1) for i, d in enumerate(gt)]
        _run_scenario(proc, alert_queue, img, dets, t=t0)
        _drain_queue(alert_queue)   # discard seed

        _run_scenario(proc, alert_queue, img, dets, t=t0 + 31.0)
        incidents = _drain_queue(alert_queue)
        loitering = [i for i in incidents if i.threat_type == "loitering"]
        assert len(loitering) == 2, "Both loiterers should generate separate incidents"
        track_ids = {i.track_id for i in loitering}
        assert {1, 2} == track_ids

    def test_high_severity_threats_take_priority_actions(
        self, mock_model, alert_queue, tmp_path, monkeypatch, dispatcher
    ):
        """Critical threats (weapon + fire) should both generate full response actions."""
        proc = _build_processor(mock_model, alert_queue, tmp_path, monkeypatch)
        img = np.zeros((480, 640, 3), dtype=np.uint8)
        dets = [
            _make_det("weapon", [50, 50, 200, 400], track_id=1),
            _make_det("fire",   [300, 50, 600, 400], track_id=2),
        ]
        _run_scenario(proc, alert_queue, img, dets)

        for _ in range(alert_queue.qsize()):
            inc = alert_queue.get_nowait()
            dispatcher.dispatch(inc)
            if inc.threat_type == "weapon":
                assert "deter:lock_gates"        in inc.actions
                assert "notify:police"           in inc.actions
            elif inc.threat_type == "fire":
                assert "deter:sprinkler_trigger" in inc.actions
                assert "notify:fire"             in inc.actions


# ─── IMAGE QUALITY SANITY CHECK ───────────────────────────────────────────────

class TestSyntheticImageSanity:
    """Verify that generated test images are valid and non-trivial."""

    @pytest.mark.parametrize("scene_fn,expected_class", [
        (scene_loitering,          "person"),
        (scene_brawl,              "brawl"),
        (scene_fire,               "fire"),
        (scene_smoke,              "smoke"),
        (scene_abandoned_bag,      "abandoned_bag"),
        (scene_crowd_surge,        "crowd_surge"),
        (scene_weapon,             "weapon"),
        (scene_vehicle_intrusion,  "vehicle_intrusion"),
        (scene_graffiti,           "graffiti_vandalism"),
        (scene_suspicious_package, "suspicious_package"),
    ])
    def test_image_is_valid_and_annotated(self, scene_fn, expected_class):
        img, scene_name, detections = scene_fn()

        # Image shape
        assert img.shape == (480, 640, 3), f"{scene_name}: wrong image dimensions"
        assert img.dtype == np.uint8

        # Not a blank image (has some non-zero pixels)
        assert img.any(), f"{scene_name}: image is completely black"

        # Ground-truth annotations present
        assert len(detections) > 0, f"{scene_name}: no detections"
        assert detections[0]["class"] == expected_class, \
            f"{scene_name}: expected class '{expected_class}'"

        # Bounding boxes within image bounds
        for det in detections:
            x1, y1, x2, y2 = det["bbox"]
            assert 0 <= x1 < x2 <= 640, f"{scene_name}: invalid x bbox"
            assert 0 <= y1 < y2 <= 480, f"{scene_name}: invalid y bbox"
